### ISSUE TITLE
SimpleChat - Globalfix

### ISSUE THREAD

**Issue by SeVen94** [Calenria/SimpleChat#1]
Hallo Calenria, (GOTT)
der Globalchat funktioniert jetzt aber allerdings die /msg Funktion nicht mehr.
Welche aber vor dem Globalchat funktionierte (natürlich nur lokal)

Vielleicht kannst du da noch was machen:)

**Comment by SeVen94** [comment]
Und eine swollte ich noch fragen wg den Permissions..
sobald man op ist funktioniert der globalchat nicht..
jetzt wollte ich auf op verzichten und meine permissions ändern nur
dann funkz der globalchat wieder nicht

  Kaiser:
    permission:
    - -simplechat.global.off
    - '*'
    options:
      rank: '1'
      prefix: '&4Kaiser'

hab es auch andersrum probiert das zuerst '_' kommt und dann simplechat.global.off hilft aber auch nichts ('_' verwende ich nur bei meinem rang..)

**Comment by zoeliterally** [comment]
PM Fix:
https://github.com/Calenria/SimpleChat/releases/tag/v0.4.4

Wegen den Permissions, mach mal '*' komplett raus und versuch obs dann noch Probleme mit OP gibt.

**Comment by SeVen94** [comment]
PM Fix funktioniert mit /w die befehle /msg und /tell funktioniert nicht da steht dort Chatpartner (null) gelöscht   die aliases habe ich auch übernommen sowie auch pmspy zeigt es trotz permission nicht an

**Comment by SeVen94** [comment]
ja gibt immernoch Probleme mit OP

**Comment by zoeliterally** [comment]
Die aliases müssen ja nun in der commands.yml eingetragen werden:

```
aliases:
  tell:
  - w $1-
  msg:
  - w $1-
  r:
  - rep $1-
  reply:
  - rep $1-
  list:
  - olist
```

Wegen OP schau ich gleich mal

**Comment by SeVen94** [comment]
Wg pmspy ist es merkwürdig hab jetzt mit. 2account und nen kumpel /msg geschrieben.. 

vom kumpel die msg kann ich via pmspy lesen aber vom 2. account nicht.

beide haben die gleichen permissions und waren auf unterschiedliche Server
1. account [server1] kumpel [server2]

ich war auch [server1]

**Comment by zoeliterally** [comment]
Hmm OP ist bei mir kein Problem:

![screenshot-screen-2015-06-08-135331](https://cloud.githubusercontent.com/assets/1536360/8034255/4847ddbc-0de6-11e5-84f7-2a19d7466e5e.png)

**Comment by SeVen94** [comment]
![2015-06-08_13 59 31](https://cloud.githubusercontent.com/assets/12796452/8034300/b05ff452-0de6-11e5-88f1-207925304013.png)

bei mir so

**Comment by SeVen94** [comment]
Also ich hab wg pmspy jetzt getestet..

das zeigt es mir nur die pms an die auf einem anderen Server sind..

wenn die auf den gleichen Server sind wie ich funkz das nicht

**Comment by zoeliterally** [comment]
Probier mal: 
https://github.com/Calenria/SimpleChat-Bungee/releases/tag/v0.4.5 
https://github.com/Calenria/SimpleChat/releases/tag/v0.4.5

**Comment by SeVen94** [comment]
Es funktioniert alles!

**Comment by SeVen94** [comment]
Danke GOTT Calenria! was sind wir dir schulding außer GOTT Titel und eigene Kirche?

**Comment by SeVen94** [comment]
schuldig\* sorry habs heute nicht so mit der Rechtschreibung ich freu mich gerade total!

**Comment by zoeliterally** [comment]
Gar nix :grinning: 

Falls noch Fehler auftreten einfach ein neues Ticket aufmachen, ich mach das hier zu.
