### ISSUE TITLE
SimpleChat - Permissions

### ISSUE THREAD

**Issue by SeVen94** [Calenria/SimpleChat#2]
Vater unser im Himmel, ( :100: )

ich wollte wg Permissions noch was fragen für meinen Rang

wie kriegt man das hin mit '*' aber das der globalchat trotzdem funktioniert?

```
permissions:
- '*'
- -simplechat.global.off
```

hab es mehrmals auch umgedreht aber funktioniert leider nicht vielleicht hat GOTT die Idee :)

**Comment by zoeliterally** [comment]
Wofür braucht man unbedingt die \* Permission? Ich hab die nie benutzt, entwender hat man OP oder alle Permissions die der Rang braucht werden eingetragen, aber \* gibt nur Probleme bei einigen Plugins die von default entzogenen Permissions ausgehen.

Ich hab auch keine ahnung wie man dem Permission Plugin verklickern könnte trotz \* eine Permission Node zu entziehen.

**Comment by SeVen94** [comment]
Ok dann verwende ich nun op danke :)!!
